services:
#    formation.example:
#        class: formationBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
# config/services.yaml

# ...
# config/services.yaml

# ...
parameters:
  brochures_directory: '%kernel.project_dir%/public/uploads/brochures'