<?php

namespace formationBundle\Repository;

/**
 * conseilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class conseilRepository extends \Doctrine\ORM\EntityRepository
{
}
