<?php

namespace GestionVoteBundle\Repository;

/**
 * dislikeJuryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dislikeJuryRepository extends \Doctrine\ORM\EntityRepository
{
}
