<?php

namespace GestionVoteBundle\Repository;

/**
 * DislikeCoachRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DislikeCoachRepository extends \Doctrine\ORM\EntityRepository
{
}
