<?php

namespace GestionVoteBundle\Repository;

/**
 * LikeJureyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeJureyRepository extends \Doctrine\ORM\EntityRepository
{
}
