<?php

namespace GestionVoteBundle\Repository;

/**
 * LikeCoachRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeCoachRepository extends \Doctrine\ORM\EntityRepository
{
}
