index:
  path:     /index
  defaults: { _controller: EvenementBundle:Frontend:index }
aboutpage:
  path:     /about
  defaults: { _controller: EvenementBundle:Frontend:about }
contactpage:
  path:     /contact
  defaults: { _controller: EvenementBundle:Frontend:contact }
evenement_list_categorie:
  path:     /evenement/show/{categorie}
  defaults: { _controller: EvenementBundle:EvenementFront:showBycategory }
evenement_show_one:
  path:     /evenement/show-one/{id}
  defaults: { _controller: EvenementBundle:EvenementFront:showoneEvenement }
publication_add:
  path:     /acess/candidat/publication/add/{eventId}
  defaults: { _controller: EvenementBundle:PublicationFrontend:create }
publication_affiche:
  path:     /acess/candidat/publication/affiche
  defaults: { _controller: EvenementBundle:PublicationFrontend:affiche }
participation_add:
  path:     /acess/candidat/participation/add/{eventId}
  defaults: { _controller: EvenementBundle:Participation:create }
showenementcalender:
  path:     /evenement/show-calender
  defaults: { _controller: EvenementBundle:EvenementFront:showoneEvenementCalender }
event_json:
  path:     /full-calendar/load-json
  defaults: { _controller: EvenementBundle:EvenementFront:getEventsJson }
publication_search_ajax:
  path:     /publication/search
  defaults: { _controller: EvenementBundle:PublicationFrontend:search }
publication_affiche_by_event:
  path:     /acess/candidat/publication/affiche/{idEvent}
  defaults: { _controller: EvenementBundle:PublicationFrontend:afficheByevent }
publication_sucess:
  path:     /acess/candidat/publication/success
  defaults: { _controller: EvenementBundle:PublicationFrontend:success }
profile_candidat:
  path:     /acess/candidat/profile
  defaults: { _controller: EvenementBundle:ProfileCandidat:profile}
publication_show_one:
  path:     /acess/candidat/publication/show/{id}
  defaults: { _controller: EvenementBundle:PublicationFrontend:showonePublication}
