<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Article;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function findA($articleId)
    {
        $qb = $this->createQueryBuilder('ce')
            ->select('ce')
            ->where('ce.Commentaire = :article_id')
            ->addOrderBy('ce.date_ajout')
            ->setParameter('blog_id', $articleId);
        return $qb->getQuery()
            ->getResult();
    }

    public function findArticle($id_article)
    {


        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQuery(
            'SELECT  a,c
            FROM AppBundle:Commentaire a
            INNER JOIN a.articles c
            WHERE c.id =:id')->setParameter('id',$id_article);


        return $query
            ->getResult();
    }
}
