security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        CANDIDAT:  ROLE_CANDIDAT
        ADMIN: ROLE_SUPER_ADMIN
        JURY: ROLE_JURY
        ROLE_SPECTATEUR: ROLE_SPECTATEUR
        SPONSOR: ROLE_SPONSOR
        COACH: ROLE_COACH

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            user_checker: security.user_checker
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                use_forward: false
                always_use_default_target_path: false
                default_target_path: /listerA

            logout:
                path:   /logout
                target: /login
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/admin/, role: ROLE_ADMIN }
        #- { path: ^/admin/, role: ROLE_ADMIN }
        #- { path: ^/listerA, role: ROLE_USER }
        #- { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/Projet/profilsponsor, role: ROLE_SPONSOR }
        #- { path: ^/Projet/Ajoutconseil, role: ROLE_COACH }
        #- { path: ^/Projet/Affichage, role: ROLE_COACH }
        - { path: ^/listerA, role: ROLE_CANDIDAT }
        #- { path: ^/acess/admin, role: ROLE_ADMIN }
#        - { path: ^/acess/candidat, role: ROLE_CANDIDAT }
#        - { path: ^/acess/jury, role: ROLE_JURY }
#        - { path: ^/acess/spectateur, role: ROLE_SPECTATEUR }
#        - { path: ^/acess/sponsor, role: ROLE_SPONSOR }
#        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
