<?php

namespace EvenementBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function getJsonList(){
      $res =  $this->createQueryBuilder('a')
            ->select('a.title as title , a.dateDebut as start , a.id as _id' )
            ->getQuery()
            ->getArrayResult();
        return $res;
    }

    public function getEventByCategory($category){
        $res = $this->createQueryBuilder("e")
            ->where('e.categories = :cat')
                ->setParameter('cat',$category)
            ->andWhere('e.dateFin >= :dateNow')
            ->setParameter('dateNow',new \DateTime())
            ->getQuery()->getResult();

        return $res;


    }

}
