<?php

namespace SponsoringBundle\Repository;

/**
 * DemandesponsoringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandesponsoringRepository extends \Doctrine\ORM\EntityRepository
{
}
